version: '3.7'

services:
  web:
    build:
      context: ../../
      dockerfile: devops/docker/Dockerfile
    ports:
      - "8000:8000"
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "main:app"]